In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [5]:
data = np.loadtxt("train.dat", encoding="utf8")

In [7]:
n_passengers = len(data)
n_survived = len(data[data[:, 1] == 1])
n_dead = len(data[data[:, 1] == 0])
print(f"Out of {n_passengers} passengers {n_survived} ({n_survived/n_passengers*100:.2f}%) survived and {n_dead} ({n_dead/n_passengers*100:.2f}%) died.")

Out of 716 passengers 268 (37.43%) survived and 448 (62.57%) died.


In [11]:
data[:,-1]

array([  7.25,  71.28,   7.92,  53.1 ,   8.05,   8.46,  11.13,  16.7 ,
        26.55,   8.05,   7.85,  16.  ,  18.  ,   7.22,  26.  ,  13.  ,
         8.03,  21.07,  31.39,   7.9 ,  27.72,   7.75,  10.5 ,  52.  ,
         7.23,   8.05,  18.  ,  11.24,   9.47,  21.  ,   7.9 ,  41.58,
         7.88,   8.05,  15.5 ,   7.75,  21.68,  17.8 ,  39.69,   7.8 ,
        76.73,  26.  ,   7.23,  27.75,  46.9 ,   7.23,  80.  ,  83.47,
        27.9 ,  27.72,  15.25,  10.5 ,   8.16,   7.92,  10.5 ,  46.9 ,
        14.45,  56.5 ,   7.65,   8.05,  29.  ,  12.47,   9.  ,   9.5 ,
         7.79,  47.1 ,  10.5 ,  15.85,  34.38,   8.05, 263.  ,   8.05,
         8.05,   7.85,  61.17,  20.57,   7.25,   8.05,  34.65,  63.36,
        23.  ,  26.  ,   7.9 ,   7.9 ,  77.29,   8.65,   7.92,   7.9 ,
         7.65,   7.78,   7.9 ,  24.15,  52.  ,  14.45,   8.05,   9.82,
         7.92,   7.75,  21.  , 247.52,  31.27,  73.5 ,   8.05,  30.07,
        13.  ,  77.29,  11.24,   7.75,   7.14,  22.36,   7.9 ,   7.05,
      

In [15]:
malecond = np.intersect1d(data[:, 1] == 1, data[:,2] == 0)
malecond

array([False,  True])

In [16]:
data[:,2] == 0

array([ True, False, False, False,  True,  True, False, False, False,
        True, False, False, False, False,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False,  True, False, False,  True,  True, False,
        True, False,  True,  True, False, False,  True, False,  True,
        True, False,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False,  True,  True, False,  True,
        True,  True, False, False, False,  True,  True,  True, False,
       False,  True,